// classroom/react/host-monitor/src/pages/HomePage.tsx
import { Navbar } from '../components/Navbar';

type HomePageProps = {
  navigate: (path: string) => void;
};

export function HomePage({ navigate }: HomePageProps) {
  return (
    <main className="home-page">
      <Navbar navigate={navigate} theme="dark" />
      <section className="hero-section">
        <div className="hero-copy">
          <p className="eyebrow cyan">Monitoramento de hosts</p>
          <h1>Host Monitor</h1>
          <p>
            Acompanhe disponibilidade, latencia e historico dos seus hosts em um painel direto
            para operacao.
          </p>
          <div className="hero-actions">
            <button className="primary-cyan" type="button" onClick={() => navigate('/login')}>
              Entrar
            </button>
            <button className="ghost-dark" type="button" onClick={() => navigate('/register')}>
              Criar conta
            </button>
          </div>
        </div>

        <div className="dashboard-preview">
          <div className="window-bar">
            <span />
            <span />
            <span />
            <strong>dashboard</strong>
          </div>
          <div className="preview-metrics">
            <article className="metric green">
              <span>Online</span>
              <strong>98.5%</strong>
              <i />
            </article>
            <article className="metric blue">
              <span>Latencia</span>
              <strong>12ms</strong>
              <div className="mini-bars">
                <b />
                <b />
                <b />
                <b />
                <b />
              </div>
            </article>
            <article className="metric red">
              <span>Alertas</span>
              <strong>1</strong>
              <i />
            </article>
          </div>
          <div className="preview-list">
            <div>
              <span>
                <strong>Google DNS</strong>
                <small>8.8.8.8</small>
              </span>
              <em className="ok">Online</em>
            </div>
            <div>
              <span>
                <strong>Servidor interno</strong>
                <small>intranet.local</small>
              </span>
              <em className="bad">Offline</em>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}

// classroom/angular/host-monitor/src/app/pages/home/home.page.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

import { NavbarComponent } from '../../layout/navbar.component';

@Component({
  selector: 'app-home-page',
  imports: [NavbarComponent, RouterLink],
  template: `
    <main class="hero-page">
      <app-navbar theme="dark" />

      <section class="hero-shell">
        <div class="hero-copy">
          <p class="eyebrow cyan">Monitoramento de hosts</p>
          <h1>Host Monitor</h1>
          <p>
            Acompanhe disponibilidade, latência e histórico dos seus hosts em um painel direto para
            operação.
          </p>
          <div class="hero-actions">
            <a class="button button-cyan" routerLink="/login">Entrar</a>
            <a class="button button-ghost-dark" routerLink="/register">Criar conta</a>
          </div>
        </div>

        <div class="terminal-preview" aria-label="Prévia do dashboard">
          <div class="terminal-bar">
            <span class="dot rose"></span>
            <span class="dot amber"></span>
            <span class="dot green"></span>
            <small>dashboard</small>
          </div>
          <div class="metric-grid">
            <article class="metric-card success">
              <span>Online</span>
              <strong>98.5%</strong>
              <div class="meter"><i style="width: 98%"></i></div>
            </article>
            <article class="metric-card info">
              <span>Latência</span>
              <strong>12ms</strong>
              <div class="mini-bars">
                <i style="height: 36%"></i>
                <i style="height: 70%"></i>
                <i style="height: 48%"></i>
                <i style="height: 90%"></i>
                <i style="height: 58%"></i>
              </div>
            </article>
            <article class="metric-card danger">
              <span>Alertas</span>
              <strong>1</strong>
              <div class="meter"><i style="width: 20%"></i></div>
            </article>
          </div>
          <div class="preview-list">
            <div>
              <span><b>Google DNS</b><small>8.8.8.8</small></span>
              <em class="pill online">Online</em>
            </div>
            <div>
              <span><b>Servidor interno</b><small>intranet.local</small></span>
              <em class="pill offline">Offline</em>
            </div>
          </div>
        </div>
      </section>
    </main>
  `,
})
export class HomePage {}
