// classroom/react/host-monitor/src/components/Navbar.tsx
import { Activity, LogOut } from 'lucide-react';

import type { AppRoute } from '../App';
import type { User } from '../types';

type NavbarProps = {
  active?: AppRoute;
  authenticated?: boolean;
  onLogout?: () => void;
  navigate: (path: string) => void;
  theme?: 'light' | 'dark';
  user?: User | null;
};

export function Navbar({
  active,
  authenticated = false,
  navigate,
  onLogout,
  theme = 'light',
  user,
}: NavbarProps) {
  return (
    <nav className={`navbar navbar-${theme}`}>
      <button
        className="brand-button"
        type="button"
        onClick={() => navigate(authenticated ? '/dashboard' : '/')}
      >
        <Activity size={18} />
        <span>HOST MONITOR</span>
      </button>

      {authenticated ? (
        <div className="nav-auth-actions">
          <button
            className={active === 'dashboard' ? 'nav-link active' : 'nav-link'}
            type="button"
            onClick={() => navigate('/dashboard')}
          >
            Dashboard
          </button>
          {active === 'host' ? <span className="nav-link active">Detalhes</span> : null}
          <a className="nav-link" href="/api/docs">
            API Docs
          </a>
          <span className="user-name">{user?.name}</span>
          <button className="nav-link logout-button" type="button" onClick={onLogout}>
            <LogOut size={16} />
            Sair
          </button>
        </div>
      ) : (
        <div className="nav-public-actions">
          <button
            className={active === 'login' ? 'nav-pill active' : 'nav-pill'}
            type="button"
            onClick={() => navigate('/login')}
          >
            Login
          </button>
          <button
            className={active === 'register' ? 'nav-pill active' : 'nav-pill'}
            type="button"
            onClick={() => navigate('/register')}
          >
            Cadastro
          </button>
        </div>
      )}
    </nav>
  );
}

// classroom/angular/host-monitor/src/app/layout/navbar.component.ts
import { Component, computed, input } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';

import { AuthService } from '../core/auth.service';

@Component({
  selector: 'app-navbar',
  imports: [RouterLink, RouterLinkActive],
  template: `
    <nav class="navbar" [class.navbar-dark]="theme() === 'dark'">
      <a class="brand" [routerLink]="auth.isAuthenticated() ? '/dashboard' : '/'"> HOST MONITOR </a>

      @if (auth.isAuthenticated()) {
        <div class="nav-actions auth-actions">
          <a
            routerLink="/dashboard"
            routerLinkActive="active-link"
            [routerLinkActiveOptions]="{ exact: true }"
            >Dashboard</a
          >
          @if (showDetails()) {
            <span class="active-link">Detalhes</span>
          }
          <a href="/api/docs" target="_blank" rel="noreferrer">API Docs</a>
          @if (auth.user()?.name) {
            <span class="user-name">{{ auth.user()?.name }}</span>
          }
          <button type="button" class="link-button" (click)="logout()">Sair</button>
        </div>
      } @else {
        <div class="nav-actions">
          <a routerLink="/login" routerLinkActive="primary-link">Login</a>
          <a routerLink="/register" routerLinkActive="primary-link">Cadastro</a>
        </div>
      }
    </nav>
  `,
})
export class NavbarComponent {
  readonly theme = input<'light' | 'dark'>('light');
  readonly context = input<'public' | 'dashboard' | 'details'>('public');
  readonly showDetails = computed(() => this.context() === 'details');

  constructor(
    readonly auth: AuthService,
    private readonly router: Router,
  ) {}

  logout(): void {
    this.auth.logout();
    void this.router.navigateByUrl('/login');
  }
}
