// classroom/angular/host-monitor/src/app/pages/login/login.page.ts
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';

import { AuthService } from '../../core/auth.service';
import { ApiError } from '../../core/models';
import { NavbarComponent } from '../../layout/navbar.component';

@Component({
  selector: 'app-login-page',
  imports: [NavbarComponent, ReactiveFormsModule, RouterLink],
  template: `
    <app-navbar />
    <main class="auth-layout">
      <section>
        <h1>Entrar</h1>
        <p>
          Acesse seu dashboard para consultar hosts, executar checks e acompanhar o histórico de
          disponibilidade.
        </p>
      </section>

      <section class="panel">
        <form class="form-grid" [formGroup]="form" (ngSubmit)="submit()">
          <label>
            <span>Email</span>
            <input type="email" formControlName="email" autocomplete="email" />
          </label>
          <label>
            <span>Senha</span>
            <input type="password" formControlName="password" autocomplete="current-password" />
          </label>
          <p class="feedback">{{ feedback() }}</p>
          <button class="button button-dark" type="submit" [disabled]="loading()">Entrar</button>
        </form>
        <p class="muted-link">Ainda não tem conta? <a routerLink="/register">Cadastre-se</a></p>
      </section>
    </main>
  `,
})
export class LoginPage {
  private readonly fb = inject(FormBuilder);
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  readonly loading = signal(false);
  readonly feedback = signal('');
  readonly form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', Validators.required],
  });

  submit(): void {
    if (this.form.invalid || this.loading()) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading.set(true);
    this.feedback.set('');
    this.auth.login(this.form.getRawValue()).subscribe({
      next: () => void this.router.navigateByUrl('/dashboard'),
      error: ({ error }: { error?: ApiError }) => {
        this.feedback.set(error?.error ?? error?.message ?? 'Não foi possível entrar.');
        this.loading.set(false);
      },
    });
  }
}

// classroom/react/host-monitor/src/pages/LoginPage.tsx
import { FormEvent, useState } from 'react';

import { Navbar } from '../components/Navbar';
import { login } from '../lib/api';
import { setSession } from '../lib/session';

type LoginPageProps = {
  navigate: (path: string) => void;
  onAuthenticated: () => void;
};

export function LoginPage({ navigate, onAuthenticated }: LoginPageProps) {
  const [feedback, setFeedback] = useState('');
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setFeedback('');
    setSubmitting(true);

    const form = new FormData(event.currentTarget);

    try {
      const session = await login({
        email: String(form.get('email') ?? ''),
        password: String(form.get('password') ?? ''),
      });
      setSession(session);
      onAuthenticated();
    } catch (error) {
      setFeedback(error instanceof Error ? error.message : 'Nao foi possivel entrar.');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <main className="page">
      <Navbar active="login" navigate={navigate} />
      <section className="auth-layout">
        <div>
          <h1>Entrar</h1>
          <p>
            Acesse seu dashboard para consultar hosts, executar checks e acompanhar o historico de
            disponibilidade.
          </p>
        </div>
        <form className="auth-panel" onSubmit={handleSubmit}>
          <label>
            <span>Email</span>
            <input autoComplete="email" name="email" required type="email" />
          </label>
          <label>
            <span>Senha</span>
            <input autoComplete="current-password" name="password" required type="password" />
          </label>
          <p className="form-feedback">{feedback}</p>
          <button className="primary-dark" disabled={submitting} type="submit">
            {submitting ? 'Entrando...' : 'Entrar'}
          </button>
          <p className="form-link">
            Ainda nao tem conta?{' '}
            <button type="button" onClick={() => navigate('/register')}>
              Cadastre-se
            </button>
          </p>
        </form>
      </section>
    </main>
  );
}
