// classroom/react/host-monitor/src/pages/DashboardPage.tsx
import { FormEvent, useEffect, useState } from 'react';
import { Plus, X } from 'lucide-react';

import { HostCard } from '../components/HostCard';
import { Navbar } from '../components/Navbar';
import { createHost, deleteHost, listHosts } from '../lib/api';
import type { Host, User } from '../types';

type DashboardPageProps = {
  navigate: (path: string) => void;
  onLogout: () => void;
  user: User | null;
};

export function DashboardPage({ navigate, onLogout, user }: DashboardPageProps) {
  const [hosts, setHosts] = useState<Host[]>([]);
  const [loading, setLoading] = useState(true);
  const [feedback, setFeedback] = useState('');
  const [modalOpen, setModalOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    let active = true;

    listHosts()
      .then((payload) => {
        if (active) {
          setHosts(payload);
        }
      })
      .catch((error) => setFeedback(error instanceof Error ? error.message : 'Erro ao buscar hosts.'))
      .finally(() => {
        if (active) {
          setLoading(false);
        }
      });

    return () => {
      active = false;
    };
  }, []);

  async function handleCreate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitting(true);
    setFeedback('');

    const form = new FormData(event.currentTarget);

    try {
      const created = await createHost({
        name: String(form.get('name') ?? ''),
        address: String(form.get('address') ?? ''),
        category: String(form.get('category') ?? ''),
      });
      setHosts((current) => [created, ...current]);
      event.currentTarget.reset();
      setModalOpen(false);
    } catch (error) {
      setFeedback(error instanceof Error ? error.message : 'Erro ao adicionar host.');
    } finally {
      setSubmitting(false);
    }
  }

  async function handleDelete(id: string) {
    setFeedback('');

    try {
      await deleteHost(id);
      setHosts((current) => current.filter((host) => host.id !== id));
    } catch (error) {
      setFeedback(error instanceof Error ? error.message : 'Erro ao excluir host.');
    }
  }

  return (
    <main className="page">
      <Navbar active="dashboard" authenticated navigate={navigate} onLogout={onLogout} user={user} />
      <section className="content">
        <header className="center-header">
          <p className="eyebrow">Painel de Hosts</p>
          <h1>Hosts disponiveis</h1>
          <p>Visualize informacoes basicas dos hosts.</p>
        </header>

        <div className="toolbar">
          <button className="primary-dark inline-icon" type="button" onClick={() => setModalOpen(true)}>
            <Plus size={18} />
            Adicionar novo host
          </button>
        </div>

        {feedback ? <p className="page-feedback">{feedback}</p> : null}

        {loading ? <p className="empty-state">Carregando hosts...</p> : null}

        {!loading && hosts.length === 0 ? <p className="empty-state">Nenhum host cadastrado ainda.</p> : null}

        <section className="host-grid">
          {hosts.map((host) => (
            <HostCard host={host} key={host.id} navigate={navigate} onDelete={handleDelete} />
          ))}
        </section>
      </section>

      {modalOpen ? (
        <div className="modal-backdrop" role="dialog" aria-modal="true" onMouseDown={() => setModalOpen(false)}>
          <form className="modal-panel" onMouseDown={(event) => event.stopPropagation()} onSubmit={handleCreate}>
            <div className="modal-header">
              <div>
                <h2>Adicionar novo host</h2>
                <p>Preencha os dados para cadastrar um host no painel.</p>
              </div>
              <button className="icon-button" type="button" onClick={() => setModalOpen(false)} aria-label="Fechar">
                <X size={18} />
              </button>
            </div>
            <label>
              <span>Nome do host</span>
              <input name="name" placeholder="Google DNS" required type="text" />
            </label>
            <label>
              <span>Endereco (IP ou dominio)</span>
              <input name="address" placeholder="8.8.8.8" required type="text" />
            </label>
            <label>
              <span>Categoria</span>
              <input name="category" placeholder="DNS" required type="text" />
            </label>
            <button className="primary-dark" disabled={submitting} type="submit">
              {submitting ? 'Adicionando...' : 'Adicionar host'}
            </button>
          </form>
        </div>
      ) : null}
    </main>
  );
}

// classroom/angular/host-monitor/src/app/pages/dashboard/dashboard.page.ts
import { DecimalPipe } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { finalize } from 'rxjs';

import { ApiError, Host } from '../../core/models';
import { HostApiService } from '../../core/host-api.service';
import { NavbarComponent } from '../../layout/navbar.component';

@Component({
  selector: 'app-dashboard-page',
  imports: [DecimalPipe, NavbarComponent, ReactiveFormsModule, RouterLink],
  template: `
    <app-navbar context="dashboard" />
    <main class="page-shell">
      <header class="page-header">
        <p class="eyebrow">Painel de Hosts</p>
        <h1>Hosts disponíveis</h1>
        <p>Visualize informações básicas dos hosts monitorados.</p>
      </header>

      <section class="toolbar">
        <button class="button button-dark" type="button" (click)="openModal()">
          Adicionar novo host
        </button>
      </section>

      @if (feedback()) {
        <p class="notice">{{ feedback() }}</p>
      }

      @if (loading()) {
        <p class="empty-state">Carregando hosts...</p>
      } @else if (!hosts().length) {
        <p class="empty-state">Nenhum host cadastrado ainda.</p>
      } @else {
        <section class="host-grid">
          @for (host of sortedHosts(); track host.id) {
            <article class="host-card">
              <div class="card-heading">
                <div>
                  <h2>{{ host.name }}</h2>
                  <p>Categoria: {{ host.category }}</p>
                </div>
                <span
                  class="status-pill"
                  [class.online]="host.status === 'Online'"
                  [class.offline]="host.status === 'Offline'"
                  [class.unknown]="host.status === 'Unknown'"
                >
                  {{ host.status }}
                </span>
              </div>

              <dl class="host-facts">
                <div>
                  <dt>Endereço</dt>
                  <dd>{{ host.address }}</dd>
                </div>
                <div>
                  <dt>Uptime</dt>
                  <dd>{{ host.uptime | number: '1.2-2' }}%</dd>
                  <div class="meter">
                    <i
                      [class]="availabilityClass(host.uptime)"
                      [style.width.%]="clamp(host.uptime)"
                    ></i>
                  </div>
                </div>
              </dl>

              <footer class="card-actions">
                <span>ID: {{ host.id.slice(0, 10) }}...</span>
                <div>
                  <a class="button button-small button-dark" [routerLink]="['/hosts', host.id]">
                    Ver detalhes
                  </a>
                  <button
                    class="button button-small button-danger"
                    type="button"
                    (click)="deleteHost(host.id)"
                  >
                    Remover
                  </button>
                </div>
              </footer>
            </article>
          }
        </section>
      }
    </main>

    @if (modalOpen()) {
      <div class="modal-backdrop" role="dialog" aria-modal="true" (click)="closeModal()">
        <section class="modal-panel" (click)="$event.stopPropagation()">
          <div class="modal-heading">
            <div>
              <h2>Adicionar novo host</h2>
              <p>Preencha os dados para cadastrar um host no painel.</p>
            </div>
            <button class="button button-ghost" type="button" (click)="closeModal()">Fechar</button>
          </div>

          <form class="form-grid" [formGroup]="form" (ngSubmit)="createHost()">
            <label>
              <span>Nome do host</span>
              <input type="text" formControlName="name" placeholder="Google DNS" />
            </label>
            <label>
              <span>Endereço (IP ou domínio)</span>
              <input type="text" formControlName="address" placeholder="8.8.8.8" />
            </label>
            <label>
              <span>Categoria</span>
              <input type="text" formControlName="category" placeholder="DNS" />
            </label>
            <p class="feedback">{{ modalFeedback() }}</p>
            <button class="button button-dark" type="submit" [disabled]="saving()">
              Adicionar host
            </button>
          </form>
        </section>
      </div>
    }
  `,
})
export class DashboardPage {
  private readonly fb = inject(FormBuilder);
  private readonly api = inject(HostApiService);

  readonly hosts = signal<Host[]>([]);
  readonly loading = signal(true);
  readonly saving = signal(false);
  readonly modalOpen = signal(false);
  readonly feedback = signal('');
  readonly modalFeedback = signal('');
  readonly sortedHosts = computed(() => [...this.hosts()].reverse());
  readonly form = this.fb.nonNullable.group({
    name: ['', Validators.required],
    address: ['', Validators.required],
    category: ['', Validators.required],
  });

  constructor() {
    this.loadHosts();
  }

  loadHosts(): void {
    this.loading.set(true);
    this.api
      .listHosts()
      .pipe(finalize(() => this.loading.set(false)))
      .subscribe({
        next: (hosts) => this.hosts.set(hosts),
        error: () => this.feedback.set('Não foi possível buscar os hosts.'),
      });
  }

  openModal(): void {
    this.modalFeedback.set('');
    this.modalOpen.set(true);
  }

  closeModal(): void {
    this.modalOpen.set(false);
  }

  createHost(): void {
    if (this.form.invalid || this.saving()) {
      this.form.markAllAsTouched();
      return;
    }

    this.saving.set(true);
    this.modalFeedback.set('');
    this.api
      .createHost(this.form.getRawValue())
      .pipe(finalize(() => this.saving.set(false)))
      .subscribe({
        next: (host) => {
          this.hosts.update((hosts) => [...hosts, host]);
          this.form.reset();
          this.closeModal();
        },
        error: ({ error }: { error?: ApiError }) => {
          this.modalFeedback.set(error?.error ?? error?.message ?? 'Erro ao adicionar host.');
        },
      });
  }

  deleteHost(id: string): void {
    this.api.deleteHost(id).subscribe({
      next: () => this.hosts.update((hosts) => hosts.filter((host) => host.id !== id)),
      error: () => this.feedback.set('Erro ao excluir host.'),
    });
  }

  clamp(value: number): number {
    return Math.max(0, Math.min(100, value));
  }

  availabilityClass(value: number): string {
    if (value >= 95) {
      return 'bar-good';
    }

    if (value >= 80) {
      return 'bar-warn';
    }

    return value > 0 ? 'bar-bad' : 'bar-empty';
  }
}
